// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: internal/grpc/service.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The request message containing the worker token.
type AuthenticateWorkerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthenticateWorkerRequest) Reset() {
	*x = AuthenticateWorkerRequest{}
	mi := &file_internal_grpc_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticateWorkerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticateWorkerRequest) ProtoMessage() {}

func (x *AuthenticateWorkerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticateWorkerRequest.ProtoReflect.Descriptor instead.
func (*AuthenticateWorkerRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_service_proto_rawDescGZIP(), []int{0}
}

func (x *AuthenticateWorkerRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// The response message containing the job details.
type AuthenticateWorkerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Authenticated bool                   `protobuf:"varint,1,opt,name=authenticated,proto3" json:"authenticated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthenticateWorkerResponse) Reset() {
	*x = AuthenticateWorkerResponse{}
	mi := &file_internal_grpc_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticateWorkerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticateWorkerResponse) ProtoMessage() {}

func (x *AuthenticateWorkerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticateWorkerResponse.ProtoReflect.Descriptor instead.
func (*AuthenticateWorkerResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_service_proto_rawDescGZIP(), []int{1}
}

func (x *AuthenticateWorkerResponse) GetAuthenticated() bool {
	if x != nil {
		return x.Authenticated
	}
	return false
}

// Request message for getting the next available job.
// Can be empty if no specific parameters are needed from the worker.
type GetNextJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNextJobRequest) Reset() {
	*x = GetNextJobRequest{}
	mi := &file_internal_grpc_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNextJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNextJobRequest) ProtoMessage() {}

func (x *GetNextJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNextJobRequest.ProtoReflect.Descriptor instead.
func (*GetNextJobRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_service_proto_rawDescGZIP(), []int{2}
}

// The request message containing the job ID.
type GetJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         int64                  `protobuf:"varint,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobRequest) Reset() {
	*x = GetJobRequest{}
	mi := &file_internal_grpc_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobRequest) ProtoMessage() {}

func (x *GetJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobRequest.ProtoReflect.Descriptor instead.
func (*GetJobRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetJobRequest) GetJobId() int64 {
	if x != nil {
		return x.JobId
	}
	return 0
}

// The response message containing the job details.
type GetJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         int64                  `protobuf:"varint,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Input         string                 `protobuf:"bytes,2,opt,name=input,proto3" json:"input,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobResponse) Reset() {
	*x = GetJobResponse{}
	mi := &file_internal_grpc_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobResponse) ProtoMessage() {}

func (x *GetJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobResponse.ProtoReflect.Descriptor instead.
func (*GetJobResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetJobResponse) GetJobId() int64 {
	if x != nil {
		return x.JobId
	}
	return 0
}

func (x *GetJobResponse) GetInput() string {
	if x != nil {
		return x.Input
	}
	return ""
}

// The request message containing the job result.
type SubmitJobResultRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         int64                  `protobuf:"varint,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Result        string                 `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"` // Result if the job completed successfully
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`   // Error message if the job failed
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitJobResultRequest) Reset() {
	*x = SubmitJobResultRequest{}
	mi := &file_internal_grpc_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitJobResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitJobResultRequest) ProtoMessage() {}

func (x *SubmitJobResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitJobResultRequest.ProtoReflect.Descriptor instead.
func (*SubmitJobResultRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_service_proto_rawDescGZIP(), []int{5}
}

func (x *SubmitJobResultRequest) GetJobId() int64 {
	if x != nil {
		return x.JobId
	}
	return 0
}

func (x *SubmitJobResultRequest) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *SubmitJobResultRequest) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// The response message for submitting a job result.
// Can be empty if no specific information needs to be returned upon successful submission.
type SubmitJobResultResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitJobResultResponse) Reset() {
	*x = SubmitJobResultResponse{}
	mi := &file_internal_grpc_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitJobResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitJobResultResponse) ProtoMessage() {}

func (x *SubmitJobResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitJobResultResponse.ProtoReflect.Descriptor instead.
func (*SubmitJobResultResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_service_proto_rawDescGZIP(), []int{6}
}

var File_internal_grpc_service_proto protoreflect.FileDescriptor

const file_internal_grpc_service_proto_rawDesc = "" +
	"\n" +
	"\x1binternal/grpc/service.proto\x12\x04vast\"1\n" +
	"\x19AuthenticateWorkerRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"B\n" +
	"\x1aAuthenticateWorkerResponse\x12$\n" +
	"\rauthenticated\x18\x01 \x01(\bR\rauthenticated\"\x13\n" +
	"\x11GetNextJobRequest\"&\n" +
	"\rGetJobRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\x03R\x05jobId\"=\n" +
	"\x0eGetJobResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\x03R\x05jobId\x12\x14\n" +
	"\x05input\x18\x02 \x01(\tR\x05input\"]\n" +
	"\x16SubmitJobResultRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\x03R\x05jobId\x12\x16\n" +
	"\x06result\x18\x02 \x01(\tR\x06result\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\x19\n" +
	"\x17SubmitJobResultResponse2\xfb\x01\n" +
	"\rWorkerService\x12Y\n" +
	"\x12AuthenticateWorker\x12\x1f.vast.AuthenticateWorkerRequest\x1a .vast.AuthenticateWorkerResponse\"\x00\x12=\n" +
	"\n" +
	"GetNextJob\x12\x17.vast.GetNextJobRequest\x1a\x14.vast.GetJobResponse\"\x00\x12P\n" +
	"\x0fSubmitJobResult\x12\x1c.vast.SubmitJobResultRequest\x1a\x1d.vast.SubmitJobResultResponse\"\x00B\x0fZ\rinternal/grpcb\x06proto3"

var (
	file_internal_grpc_service_proto_rawDescOnce sync.Once
	file_internal_grpc_service_proto_rawDescData []byte
)

func file_internal_grpc_service_proto_rawDescGZIP() []byte {
	file_internal_grpc_service_proto_rawDescOnce.Do(func() {
		file_internal_grpc_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_grpc_service_proto_rawDesc), len(file_internal_grpc_service_proto_rawDesc)))
	})
	return file_internal_grpc_service_proto_rawDescData
}

var file_internal_grpc_service_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_internal_grpc_service_proto_goTypes = []any{
	(*AuthenticateWorkerRequest)(nil),  // 0: vast.AuthenticateWorkerRequest
	(*AuthenticateWorkerResponse)(nil), // 1: vast.AuthenticateWorkerResponse
	(*GetNextJobRequest)(nil),          // 2: vast.GetNextJobRequest
	(*GetJobRequest)(nil),              // 3: vast.GetJobRequest
	(*GetJobResponse)(nil),             // 4: vast.GetJobResponse
	(*SubmitJobResultRequest)(nil),     // 5: vast.SubmitJobResultRequest
	(*SubmitJobResultResponse)(nil),    // 6: vast.SubmitJobResultResponse
}
var file_internal_grpc_service_proto_depIdxs = []int32{
	0, // 0: vast.WorkerService.AuthenticateWorker:input_type -> vast.AuthenticateWorkerRequest
	2, // 1: vast.WorkerService.GetNextJob:input_type -> vast.GetNextJobRequest
	5, // 2: vast.WorkerService.SubmitJobResult:input_type -> vast.SubmitJobResultRequest
	1, // 3: vast.WorkerService.AuthenticateWorker:output_type -> vast.AuthenticateWorkerResponse
	4, // 4: vast.WorkerService.GetNextJob:output_type -> vast.GetJobResponse
	6, // 5: vast.WorkerService.SubmitJobResult:output_type -> vast.SubmitJobResultResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_grpc_service_proto_init() }
func file_internal_grpc_service_proto_init() {
	if File_internal_grpc_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_grpc_service_proto_rawDesc), len(file_internal_grpc_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_grpc_service_proto_goTypes,
		DependencyIndexes: file_internal_grpc_service_proto_depIdxs,
		MessageInfos:      file_internal_grpc_service_proto_msgTypes,
	}.Build()
	File_internal_grpc_service_proto = out.File
	file_internal_grpc_service_proto_goTypes = nil
	file_internal_grpc_service_proto_depIdxs = nil
}
